// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.11.4
// source: utxo.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UTXO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OutputId  []byte `protobuf:"bytes,1,opt,name=outputId,proto3" json:"outputId,omitempty"`
	SoureId   []byte `protobuf:"bytes,2,opt,name=SoureId,proto3" json:"SoureId,omitempty"`
	SourcePos uint32 `protobuf:"varint,3,opt,name=SourcePos,proto3" json:"SourcePos,omitempty"`
	Amount    uint64 `protobuf:"varint,4,opt,name=Amount,proto3" json:"Amount,omitempty"`
	Address   []byte `protobuf:"bytes,5,opt,name=Address,proto3" json:"Address,omitempty"`
	ScriptPk  []byte `protobuf:"bytes,6,opt,name=ScriptPk,proto3" json:"ScriptPk,omitempty"`
}

func (x *UTXO) Reset() {
	*x = UTXO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_utxo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UTXO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UTXO) ProtoMessage() {}

func (x *UTXO) ProtoReflect() protoreflect.Message {
	mi := &file_utxo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UTXO.ProtoReflect.Descriptor instead.
func (*UTXO) Descriptor() ([]byte, []int) {
	return file_utxo_proto_rawDescGZIP(), []int{0}
}

func (x *UTXO) GetOutputId() []byte {
	if x != nil {
		return x.OutputId
	}
	return nil
}

func (x *UTXO) GetSoureId() []byte {
	if x != nil {
		return x.SoureId
	}
	return nil
}

func (x *UTXO) GetSourcePos() uint32 {
	if x != nil {
		return x.SourcePos
	}
	return 0
}

func (x *UTXO) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *UTXO) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *UTXO) GetScriptPk() []byte {
	if x != nil {
		return x.ScriptPk
	}
	return nil
}

var File_utxo_proto protoreflect.FileDescriptor

var file_utxo_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x75, 0x74, 0x78, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x20, 0x63, 0x68,
	0x61, 0x69, 0x6e, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x74, 0x78, 0x64, 0x62, 0x2e, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x22, 0xa8,
	0x01, 0x0a, 0x04, 0x55, 0x54, 0x58, 0x4f, 0x12, 0x1a, 0x0a, 0x08, 0x6f, 0x75, 0x74, 0x70, 0x75,
	0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x6f, 0x75, 0x74, 0x70, 0x75,
	0x74, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x53, 0x6f, 0x75, 0x72, 0x65, 0x49, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x53, 0x6f, 0x75, 0x72, 0x65, 0x49, 0x64, 0x12, 0x1c, 0x0a,
	0x09, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x50, 0x6f, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x09, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x50, 0x6f, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x41,
	0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x41, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1a, 0x0a,
	0x08, 0x53, 0x63, 0x72, 0x69, 0x70, 0x74, 0x50, 0x6b, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x08, 0x53, 0x63, 0x72, 0x69, 0x70, 0x74, 0x50, 0x6b, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x3b, 0x74,
	0x79, 0x70, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_utxo_proto_rawDescOnce sync.Once
	file_utxo_proto_rawDescData = file_utxo_proto_rawDesc
)

func file_utxo_proto_rawDescGZIP() []byte {
	file_utxo_proto_rawDescOnce.Do(func() {
		file_utxo_proto_rawDescData = protoimpl.X.CompressGZIP(file_utxo_proto_rawDescData)
	})
	return file_utxo_proto_rawDescData
}

var file_utxo_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_utxo_proto_goTypes = []interface{}{
	(*UTXO)(nil), // 0: chain.core.txdb.internal.storage.UTXO
}
var file_utxo_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_utxo_proto_init() }
func file_utxo_proto_init() {
	if File_utxo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_utxo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UTXO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_utxo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_utxo_proto_goTypes,
		DependencyIndexes: file_utxo_proto_depIdxs,
		MessageInfos:      file_utxo_proto_msgTypes,
	}.Build()
	File_utxo_proto = out.File
	file_utxo_proto_rawDesc = nil
	file_utxo_proto_goTypes = nil
	file_utxo_proto_depIdxs = nil
}
